### ISSUE TITLE
build contact page 

### ISSUE THREAD

**Issue by zakiyyahmandisa** [Capstone-Group-Project/DevStyle#4]

**Comment by Jawanza09** [comment]
<!DOCTYPE html>
<html>
<head>          
      <title>Connect with us</title>
</head>
<body> 
    <h3>Contact Form</h3>
    <form id="enter-name" class="ent-name-class" method="post"  action="contact-form-process.php">

<label for="Name" class="name-label">Your name</label>
<div class="name-input-group">
    <input type="text" id="Name" name="Name" class="name-form-control" required>
</div>

<label for="Email" class="email-label">Best Email for you</label>
<div class="email-input-group">
    <input type="email" id="Email" name="Email" class="email-form-control" required>
</div>

<div class="message-form-group">
    <label for="Message" class="message-label">Message us</label>   
    <div class="message-input-group">
        <textarea is="Message" name="Message" class="Message-form-control" rows="6" maxlength="2000" required></textarea>
    </div>
<div class="Submit-form-group">
    <button type="submit" id="Submit-button" class="submit-btn submit-btn-primary submit-btn-lg submit-btn-block">Send</button>
</div>

</body>
</html>
